name: Check Self-hosted runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "The self-hosted is alive!"
